name: Deploy to Firebase Hosting
on:
    workflow_call:
jobs:
    build_and_preview:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
            - name: Install Node modules
              run: cd app/ && npm install
            - name: Build
              run: cd app/ && npm run build
            - name: Check if Secret Exists
              env:
                  super_secret: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
              if: env.super_secret == ''
              run: echo "No secret found"
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BRYCE_JACKSON_WEBSITE }}
                  projectId: bryce-jackson-website
