on:
    workflow_call:

jobs:
    deploy-firebase-functions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "18"
            - name: Install Node modules
              run: cd functions/ && npm install
            - name: Build
              run: cd functions/ && npm run build
            - name: Write Secrets
              run: |
                  cd functions 
                  cd service-account-keys
                  echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ADMINSDK }}" > bryce-jackson-website-firebase-adminsdk-ra4es-7428ff5320.json
                  cat bryce-jackson-website-firebase-adminsdk-ra4es-7428ff5320.json
            - name: Deploy
              run: cd functions/ && npx firebase-tools use prod && npx firebase-tools deploy --only functions
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
