name: Deploy Dev
on:
    workflow_run:
        workflows: ["CI"]
        types:
            - completed
        branches:
            - dev

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "16"
            - name: Install Node modules
              run: echo 'hi'
